# Generated by Django 4.0.1 on 2022-01-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enfermedadcrohn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_eventos', models.CharField(blank=True, max_length=30, null=True)),
                ('imc', models.CharField(blank=True, max_length=30, null=True)),
                ('altura', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.CharField(blank=True, max_length=30, null=True)),
                ('peso', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_tratamiento', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'CROHN',
            },
        ),
    ]
