# Generated by Django 4.0.1 on 2022-02-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedadcrohn',
            name='tiempo',
        ),
    ]
