# Generated by Django 4.0.1 on 2022-02-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0002_remove_enfermedadcrohn_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedadcrohn',
            name='edad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enfermedadcrohn',
            name='sexo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
