# Generated by Django 4.0.1 on 2022-07-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0004_alter_enfermedadcrohn_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedadcrohn',
            name='tipo_tratamiento',
            field=models.CharField(blank=True, default=1, max_length=30, null=True),
        ),
    ]
